# Generated by Django 4.2.2 on 2023-08-30 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_schedule_day_of_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='teacher',
        ),
    ]
