# Generated by Django 4.2.2 on 2023-09-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='program',
            field=models.CharField(choices=[('MATH', 'Mathematics'), ('CS', 'Computer Science'), ('CTI', 'Computers and Information Technology'), ('DEFAULT', 'Default')], default='DEFAULT', max_length=45),
        ),
    ]
