# Generated by Django 4.2.1 on 2023-06-04 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='program',
            field=models.CharField(choices=[('MATH', 'Mathematics'), ('APPLIEDMATH', 'Applied Mathematics'), ('CSMATH', 'Mathematics and Computer Science'), ('CS', 'Computer Science'), ('CTI', 'Computers and Information Technology')], default='none', max_length=50),
            preserve_default=False,
        ),
    ]
