# Generated by Django 4.2.2 on 2023-06-08 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
