# Generated by Django 4.2.2 on 2023-08-30 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_teacher_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='courses',
        ),
    ]
