# Generated by Django 4.2.2 on 2023-09-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_teacher_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(default='0712345678', max_length=15),
            preserve_default=False,
        ),
    ]
