# Generated by Django 4.2.2 on 2023-09-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_teacher_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.CharField(choices=[('MATH', 'Mathematics'), ('CS', 'Computer Science'), ('CTI', 'Computers and Information Technology')], max_length=50),
        ),
    ]
